FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
# https://qiita.com/takumiw/items/2555fb1070a5014a94bc
# https://hub.docker.com/r/nvidia/cuda/tags?page=1&ordering=last_updated&name=ubuntu18

ENV TZ Asia/Tokyo

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    curl \
    make \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    vim \
    graphviz \
    sudo \
    git \


# https://github.com/anibali/docker-pytorch/blob/master/dockerfiles/1.7.0-cuda11.0-ubuntu20.04/Dockerfile

#USER user

# All users can use /home/user as their home directory
#ENV HOME=/home/user
#RUN chmod 777 /home/user

#CMD ["/bin/bash"]